import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import type { Context } from '@deepseek-ai/cordis'
import type { SubprocessRuntime, SubprocessHandle } from '@deepseek-ai/dsh-subprocess'
import { WebError } from '@deepseek-ai/dsh-web'
import type { WebSearchProvider,WebSearchRequest,WebSearchResult,WebSearchSource } from '@deepseek-ai/dsh-web'
import { CodexSearchWire } from './wire.ts'
export const CODEX_PROVIDER_ID='codex'
export const WEB_ABORTED='WEB_ABORTED', WEB_PROVIDER_ERROR='WEB_PROVIDER_ERROR', WEB_PROVIDER_PROTOCOL='WEB_PROVIDER_PROTOCOL', WEB_INVALID_CONFIG='WEB_INVALID_CONFIG'
export const CODEX_AUTH_MESSAGE='Sign in with the Codex CLI (codex login) and retry; DSH does not read provider credentials'
export const CODEX_MISSING_MESSAGE='Codex CLI is unavailable; install Codex and retry; DSH does not read provider credentials'
export interface CodexSearchProviderOptions { cwd:string;requestTimeoutMs:number;disposeGraceMs:number;maxResults:number;maxPayloadBytes:number;executable?:string }
export class CodexSearchProvider implements WebSearchProvider { readonly id=CODEX_PROVIDER_ID; private active=new Set<{ handle:SubprocessHandle;wire:CodexSearchWire }>(); constructor(private readonly subprocess:SubprocessRuntime,private readonly o:CodexSearchProviderOptions){}
  available(){return this.valid() && (!!this.o.executable || existsSync(requireCodexWrapper()))}
  async search(req:WebSearchRequest, signal?:AbortSignal):Promise<WebSearchResult>{if(!this.valid())throw new WebError('invalid Codex provider configuration',WEB_INVALID_CONFIG); const ac=new AbortController(); const timer=setTimeout(()=>{ ac.abort('timeout'); },this.o.requestTimeoutMs); const abort=()=>{ ac.abort(signal?.reason ?? 'aborted'); }; signal?.addEventListener('abort',abort,{ once:true }); let h:SubprocessHandle|undefined,w:CodexSearchWire|undefined; try{const exe=this.o.executable ?? await this.subprocess.resolveExecutable(wrapper(),undefined,ac.signal); h=this.subprocess.spawn({ argv:[...this.o.executable?[this.o.executable]:[process.execPath,exe],'app-server','--stdio'],cwd:this.o.cwd,stdio:{ stdin:'pipe',stdout:'pipe',stderr:{ maxBytes:this.o.maxPayloadBytes } },graceMs:this.o.disposeGraceMs,signal:ac.signal }); if(!h.stdout||!h.stdin)throw new Error('missing Codex pipes'); w=new CodexSearchWire(h.stdout,h.stdin); this.active.add({ handle:h,wire:w }); w.start(); const r=await w.run(this.o.cwd,req.query,ac.signal); await h.done; return normalize(r,this.o.maxResults,this.o.maxPayloadBytes)}catch(e){if(signal?.aborted)throw new WebError('Codex web search aborted',WEB_ABORTED,{ cause:e });if(ac.signal.aborted)throw new WebError('Codex web search timed out after '+this.o.requestTimeoutMs+' ms',WEB_PROVIDER_ERROR,{ cause:e });if(e instanceof WebError)throw e;throw new WebError('Codex web search failed',WEB_PROVIDER_ERROR,{ cause:e })}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort);if(w){w.interrupt();w.close()}if(h){h.terminate();await h.waitForExit().catch(()=>{})} for(const x of [...this.active])if(x.handle===h)this.active.delete(x)}}
  private valid(){return this.o.cwd.trim()!==''&&Number.isSafeInteger(this.o.requestTimeoutMs)&&this.o.requestTimeoutMs>0&&Number.isSafeInteger(this.o.disposeGraceMs)&&this.o.disposeGraceMs>0&&Number.isSafeInteger(this.o.maxResults)&&this.o.maxResults>0&&Number.isSafeInteger(this.o.maxPayloadBytes)&&this.o.maxPayloadBytes>=1048}
}
function wrapper(){return requireCodexWrapper()}
function requireCodexWrapper(){ const paths=['../../../../node_modules/@openai/codex/bin/codex.js','../../../node_modules/@openai/codex/bin/codex.js'].map(p=>fileURLToPath(new URL(p,import.meta.url))); return paths.find(p=>existsSync(p)) ?? paths[0]! }
function normalize(r:{ sources:Record<string,unknown>[];answer?:string },cap:number,bytes:number):WebSearchResult{const seen=new Set<string>(),sources:WebSearchSource[]=[];for(const x of r.sources){if(typeof x.url!=='string'||!URL.canParse(x.url)||!/^https?:$/.test(new URL(x.url).protocol)||seen.has(x.url))continue;seen.add(x.url);sources.push({ url:x.url,...typeof x.title==='string'?{ title:x.title }: {},...typeof x.snippet==='string'?{ snippet:x.snippet }: {},...typeof x.publishedAt==='string'?{ publishedAt:x.publishedAt }: {} })}let truncated=sources.length>cap;sources.splice(cap);let content=typeof r.answer==='string'?r.answer:undefined;while(JSON.stringify({ content,sources }).length>bytes){truncated=true;if(content)content=content.slice(0,Math.max(0,content.length-256));else sources.pop()}return { sources,truncated,...content?{ content }: {} }}
