import type { Readable, Writable } from 'node:stream'
import { JsonRpcLineTransport } from '@deepseek-ai/dsh-sdk-protocol'
type Obj=Record<string,unknown>
const obj=(v:unknown,l:string):Obj=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('invalid '+l);return v as Obj}
const id=(v:unknown,l:string):string=>{if(typeof v!=='string'||!v)throw new Error('invalid '+l);return v}
export interface CodexTurnResult { sources: Obj[]; answer?: string }
export class CodexSearchWire { private readonly t:JsonRpcLineTransport; private thread?:string; private turn?:string; private done=Promise.withResolvers<Obj>(); private items:Obj[]=[]; private closed=false; private fatal=Promise.withResolvers<never>()
 constructor(input:Readable,output:Writable){this.t=new JsonRpcLineTransport(input,output); void this.fatal.promise.catch(()=>{}); this.t.onRequest(m=>m==='currentTime/read'?Promise.resolve({ currentTimeAt:Math.floor(Date.now()/1000) }):Promise.reject(new Error('unsupported request '+m))); this.t.onNotification((m,p)=>{try{this.note(m,p)}catch(e){this.fatal.reject(e)}})}
  start(){this.t.start()}
  async run(cwd:string,query:string,signal:AbortSignal):Promise<CodexTurnResult>{ obj(await this.guard(this.t.request('initialize',{ clientInfo:{ name:'deepseek-harness',title:'DeepSeek Harness',version:'0.0.1' },capabilities:{ experimentalApi:false,requestAttestation:false } },signal),signal),'initialize'); this.t.notify('initialized'); await this.guard(this.t.flush(),signal); const tr=obj(await this.guard(this.t.request('thread/start',{ cwd,ephemeral:true,approvalPolicy:'never',sandbox:'read-only',config:{ web_search:'live',tools:{ web_search:true } } },signal),signal),'thread'); const th=obj(tr.thread,'thread'); if(th.ephemeral!==true)throw new Error('thread is not ephemeral'); this.thread=id(th.id,'thread id'); const rr=obj(await this.guard(this.t.request('turn/start',{ threadId:this.thread,input:[{ type:'text',text:'Use the built-in web search exactly once. Search exactly as supplied: '+query+'. Use no other tools and return source URLs and snippets.',text_elements:[] }] },signal),signal),'turn'); const tu=obj(rr.turn,'turn'); this.turn=id(tu.id,'turn id'); const early=this.done.promise; const terminal=await this.guard(early,signal); if(terminal.status!=='completed')throw new Error('turn did not complete'); return this.parse()}
  interrupt(){if(this.thread&&this.turn&&!this.closed)void this.t.request('turn/interrupt',{ threadId:this.thread,turnId:this.turn }).catch(()=>{})}
  close(){if(!this.closed){this.closed=true;this.t.close()}}
  private async guard<T>(p:Promise<T>,s:AbortSignal):Promise<T>{if(s.aborted){void p.catch(()=>{});throw new Error('aborted')} return Promise.race([p,this.fatal.promise,new Promise<T>((_,r)=>{ s.addEventListener('abort',()=>r(new Error('aborted')),{ once:true }); })])}
  private note(m:string,p:Obj){if(m==='item/completed'){if(p.threadId!==this.thread)return;if(p.turnId!==this.turn)return;const i=obj(p.item,'item');if(i.type==='webSearch')this.items.push(i)} else if(m==='turn/completed'){if(p.threadId!==this.thread)return;const x=obj(p.turn,'turn');if(id(x.id,'turn id')===this.turn)this.done.resolve(x)}}
  private parse():CodexTurnResult{const sources:Obj[]=[];let answer:string|undefined;for(const i of this.items){const rs=Array.isArray(i.results)?i.results:[];for(const r of rs){const x=obj(r,'result');if(typeof x.url==='string')sources.push(x)} if(typeof i.final_answer==='string')answer=i.final_answer} return { sources,...answer!==undefined?{ answer }: {} }}
}
